openapi: 3.0.3
info:
  title: API.Rasp.Yandex.Net
  description: API Яндекс.Расписаний
  version: 3.0.0
servers:
- url: https://api.rasp.yandex.net
tags:
- name: Список ближайших станций
  description: Список ближайших станций
paths:
  /v3.0/schedule/:
    get:
      tags:
      - getScheduleRouteByStation
      summary: "Расписание рейсов по станции"
      operationId: getScheduleRouteByStation
      parameters:
      - name: apikey
        in: query
        description: API Key
        required: true
        schema:
          type: string
      - name: station
        in: query
        description: Код станции
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleRouteByStation'
        "400":
          description: неверный запрос (ошибка клиента)
        "401":
          description: несанкционированный доступ (отсутствует или неверный API-ключ)
        "404":
          description: Ресурс не найден
  /v3.0/nearest_stations/:
    get:
      tags:
      - getNearestStations
      summary: Список ближайших станций
      operationId: getNearestStations
      parameters:
      - name: apikey
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: lat
        in: query
        description: Широта
        required: true
        schema:
          type: number
      - name: lng
        in: query
        description: Долгота
        required: true
        schema:
          type: number
      - name: distance
        in: query
        description: Радиус охвата
        required: true
        schema:
          type: integer
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      - name: lang
        in: query
        description: lang
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stations'
        "400":
          description: неверный запрос (ошибка клиента)
        "401":
          description: несанкционированный доступ (отсутствует или неверный API-ключ)
        "404":
          description: Ресурс не найден
  /v3.0/stations_list/:
    get:
      tags:
      - getAllStationsList
      summary: Список всех доступных станций
      operationId: getAllStationsList
      parameters:
      - name: apikey
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/AllStationsList'
        "400":
          description: неверный запрос (ошибка клиента)
        "401":
          description: несанкционированный доступ (отсутствует или неверный API-ключ)
        "404":
          description: Ресурс не найден
components:
  schemas:
    ScheduleRouteByStation:
      type: object
      properties:
        date: 
          type: string
        pagination:
          $ref: '#/components/schemas/Pagination'
          description: Информация о постраничном выводе
        station:
          $ref: '#/components/schemas/StationRoute'
          description: Список станций
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleRoute'
            description: Cписок рейсов
        schedule_direction:
          $ref: '#/components/schemas/Schedule_directions'
          description: Код и название запрошенного направления рейсов
        directions:
          $ref: '#/components/schemas/Directions'
          description: Коды и названия возможных направлений движения электричек по станции
    StationRoute:
      type: object
      properties:
        code:
          type: string
          description: Код станции 
        station_type:
          type: string
          description: Тип станции   
#           enum:
#            - station - станция;
#            - platform — платформа;
#            - stop — остановочный пункт;
#            - checkpoint — блок-пост;
#            - post — пост;
#            - crossing — разъезд;
#            - overtaking_point — обгонный пункт;
#            - train_station — вокзал;
#            - airport — аэропорт;
#            - bus_station — автовокзал;
#            - bus_stop — автобусная остановка;
#            - unknown — станция без типа;
#            - port — порт;
#            - port_point — портпункт;
#            - wharf — пристань;
#            - river_port — речной вокзал;
#            - marine_station — морской вокзал.
        station_type_name: 
          type: string
          description: название типа станции
        title: 
          type: string
          description: Название станции
        popular_title: 
          type: string
          description: Общепринятое название станции  
        short_title: 
          type: string
          description: Сокращенное название станции
        codes_stations:
          $ref: '#/components/schemas/CodesStations'
        transport_type:
          type: string
          description: Тип транспорта, обслуживаемый станцией
        type:
          type: string
          description: Вид станции
    ScheduleRoute:
      type: object
      properties:
        except_days:
          type: string
          description: Дни в которые нитка не курсирует
        arrival:
          type: string
          description: Время прибытия
        thread:
          $ref: '#/components/schemas/Thread'
        is_fuzzy:
          type: boolean
          description: Признак неточности времени отправления и времени прибытия
        days:
          type: string
          description: Дни курсирования нитки
        stops:
          type: string
          description: Станции следования рейса, на которых совершается остановка
        departure:
          type: string
          description: Время отправления
        terminal:
          type: string
          description: Терминал аэропрта
        platform:
          type: string
          description: Платформа или путь с которого отправляется рейс
    CodesStations:
      type: object
      properties:
        yandex: 
          type: string
          description: Код станции в системе кодирования Яндекс Расписаний
        esr:
          type: string
          description: Код станции в системе кодирования ESR
    Schedule_directions:
      type: object
      properties:
        code:
          type: string
          description: Код направления
        title:
          type: string
          description: Название направления
    Thread:
      type: object
      properties:
        uid:
          type: string
          description: Идентификатор нитки в системе кодирования Яндекс Расписаний
        title:
          type: string
          description: Название нитки
        number:
          type: string
          description: Номер рейса
        short_title:
          type: string
          description: Сокращенное название нитки
        carrier:
          $ref: '#/components/schemas/Carrier'
        transport_type:
          type: string
          description: Тип транспортного средства
        vehicle:
          type: string
          description: Название транспортного средства
        transport_subtype:
          type: string
          description: Подтип транспорта
        express_type:
          type: string
          description: Признак транспрорта, экспресс или аэроэкспресс
    Codes:
      type: object
      properties:
        icao:
          type: string
          description: Код станции в системе кодирования ICAO
        sirena:
          type: string
          description: Код станции в системе кодирования Sirena
        iata:
          type: string
          description: Код станции в системе кодирования IATA
    Transport_subtype:
      type: object
      properties:
        color:
          type: string
          description: Цвет транспортного средства в шеснадцатизначном формате
        code:
          type: string
          description: Код транспортного средства
        title:
          type: string
          description: Описание подтипа транспортного средства
    Carrier:
      type: object
      properties:
        code:
          type: integer
          description: Код перевозчика в системе кодирования Яндекс Расписаний
        codes:
          $ref: '#/components/schemas/Codes'
        title:
          type: string
          description: Название перевозчика
    Directions:
      type: object
      properties:
        code:
          type: string
          description: Код направления
        title:
          type: string
          description: Название направления
    Stations:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
          description: Информация о количестве станций, удовлетворяющих условиям поиска
        stations:
          type: array
          items:
            $ref: '#/components/schemas/Station'
            description: Список станций, удовлетворяющих условиям поиска
    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: Общее количество станций, удовлетворяющих условиям поиска
        limit:
          type: integer
          description: Ограничение на количество станций, которые Яндекс Расписания возвращают в ответе на запрос
        offset:
          type: integer
          description: Смещение относительно первого результата поиска
    Station:
      type: object
      properties:
        distance:
          type: number
          description: Расстояние от указанной в запросе точки до полученной в ответе станции
        code:
          type: string
          description: Код станции в системе кодирования Яндекс Расписаний
        station_type:
          type: string
          description: Тип станции
        station_type_name:
          type: string
          description: Название типа станции
        type_choices:
          $ref: '#/components/schemas/Schedule'
          description: Типы расписаний, доступные для станции 
        title:
          type: string
          description: Название станции
        popular_title:
          type: string
          description: Популярное название станции
        short_title:
          type: string
          description: Краткое название станции
        majority:
          type: integer
          description: Целое число, определяющее относительную важность станции в транспортном сообщении региона
        transport_type:
          type: string
          description: Основной тип транспорта для данной станции
        lat:
          type: number
          description: Широта станции
        lng:
          type: number
          description: Долгота станции
        type:
          type: string
          description: Вид найденного пункта
    Schedule:
      type: object
      properties:
        desktop_url:
          type: string
        touch_url:
          type: string
    AllStationsList:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/Countries'
            description: Список стран
    Countries:
      type: object
      properties:
        regions:
          type: array
          items:
            $ref: '#/components/schemas/Regions'
            description: Список регионов
        codes:
          $ref: '#/components/schemas/CodesCountries'
          description: Коды стран
        title:
          type: string
          description: Название страны
    CodesCountries:
      type: object
      properties:
        yandex_code:
          type: string
          description: Код страны в системе кодирования Яндекс Расписаний
    Regions:
      type: object
      properties:
        settlements:
          type: array
          items:
            $ref: '#/components/schemas/Settlements'
            description: Список населенных пунктов
        codes:
          $ref: '#/components/schemas/CodesRegions'
          description: Коды регионов
        title:
          type: string
          description: Название региона
    CodesRegions:
      type: object
      properties:
        yandex_code:
          type: string
          description: Код региона в системе кодирования Яндекс Расписаний
    Settlements:
      type: object
      properties:
        title:
          type: string
          description: Название населенного пункта
        codes:
          $ref: '#/components/schemas/CodesSettlements'
          description: Коды населенных пунктов
        stations:
          $ref: '#/components/schemas/StationsInSettlements'
          description: Список станций
    CodesSettlements:
      type: object
      properties:
        yandex_code:
          type: string
          description: Код населенного пункта в системе кодирования Яндекс Расписаний
    StationsInSettlements:
      type: object
      properties:
        direction:
          type: string
          description: Направление движания поездов
        codes:
          $ref: '#/components/schemas/CodesStations'
          description: Список кодов станций
        station_type:
          type: string
          description: Тип станции
        title:
          type: string
          description: Название станции
        longitude:
          type: integer
          description: Долгота станции
        transport_type:
          type: string
          description: Тип транспорта
        latitude:
          type: integer
          description: Широта станции
    # Stations/Codes:
    #   type: object
    #   properties:
    #     esr_code:
    #       type: string
    #       description: Код станции в системе кодирования ESR
    #     yandex_code:
    #       type: string
    #       description: Код станции в системе кодирования Яндекс Расписаний