openapi: 3.0.3
info:
  title: API.Rasp.Yandex.Net
  description: API Яндекс.Расписаний
  version: 3.0.0
servers:
- url: https://api.rasp.yandex.net
tags:
- name: Список ближайших станций
  description: Список ближайших станций
paths:
  /v3.0/schedule/:
    get:
      tags:
      - getNearestRoute
      summary: "Расписание рейсов по станции"
      operationId: getNearestRoute
      parameters:
      - name: apikey
        in: query
        description: API Key
        required: true
        schema:
          type: string
      - name: station
        in: query
        description: Код станции
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        "400":
          description: Нет данных
        "401":
          description: Нет данных
        "404":
          description: Не найдено
  /v3.0/nearest_stations/:
    get:
      tags:
      - getNearestStations
      summary: Список ближайших станций
      operationId: getNearestStations
      parameters:
      - name: apikey
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: lat
        in: query
        description: Широта
        required: true
        schema:
          type: number
      - name: lng
        in: query
        description: Долгота
        required: true
        schema:
          type: number
      - name: distance
        in: query
        description: Радиус охвата
        required: true
        schema:
          type: integer
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      - name: lang
        in: query
        description: lang
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stations'
  /v3.0/stations_list/:
    get:
      tags:
      - getAllStationsList
      summary: Список всех доступных станций
      operationId: getAllStationsList
      parameters:
      - name: apikey
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: json или xml
        required: false
        schema:
          type: string
      responses:
        "200":
          description: Успешное выполнение запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllStationsList'
        "400":
          description: Нет данных
        "401":
          description: Нет данных
        "404":
          description: Не найдено
components:
  schemas:
    Route:
      type: object
      properties:
        date: 
          type: string
        pagination:
          $ref: '#/components/schemas/Pagination'
        station:
          $ref: '#/components/schemas/StationRoute'
        schedule:
          type: array
          item:
            $ref: '#/components/schemas/ScheduleRoute'
        schedule_direction:
          $ref: '#/components/schemas/Schedule_directions'
        directions:
          $ref: '#/components/schemas/Directions'
    StationRoute:
      type: object
      properties:
        code:
          type: string
          description: Код станции 
        station_type:
          type: string
          description: Тип станции   
#           enum:
#            - station - станция;
#            - platform — платформа;
#            - stop — остановочный пункт;
#            - checkpoint — блок-пост;
#            - post — пост;
#            - crossing — разъезд;
#            - overtaking_point — обгонный пункт;
#            - train_station — вокзал;
#            - airport — аэропорт;
#            - bus_station — автовокзал;
#            - bus_stop — автобусная остановка;
#            - unknown — станция без типа;
#            - port — порт;
#            - port_point — портпункт;
#            - wharf — пристань;
#            - river_port — речной вокзал;
#            - marine_station — морской вокзал.
        station_type_name: 
          type: string
          description: название типа станции
        title: 
          type: string
          description: Название станции
        popular_title: 
          type: string
          description: Общепринятое название станции  
        short_title: 
          type: string
          description: Сокращенное название станции
        codes_stations:
          $ref: '#/components/schemas/CodesStations'
        transport_type:
          type: string
          description: Тип транспорта, обслуживаемый станцией
        type:
          type: string
          description: Вид станции
    ScheduleRoute:
      type: object
      properties:
        except_days:
          type: string
          description: Дни в которые нитка не курсирует
        arrival:
          type: string
          description: Время прибытия
        thread:
          $ref: '#/components/schemas/Thread'
        is_fuzzy:
          type: boolean
          description: Признак неточности времени отправления и времени прибытия
        days:
          type: string
          description: Дни курсирования нитки
        stops:
          type: string
          description: Станции следования рейса, на которых совершается остановка
        departure:
          type: string
          description: Время отправления
        terminal:
          type: string
          description: Терминал аэропрта
        platform:
          type: string
          description: Платформа или путь с которого отправляется рейс
    CodesStations:
      type: object
      properties:
        yandex: 
          type: string
          description: Код станции в системе кодирования Яндекс Расписаний
        esr:
          type: string
          description: Код станции в системе кодирования ESR
    Schedule_directions:
      type: object
      properties:
        code:
          type: string
          description: Код направления
        title:
          type: string
          description: Название направления
    Thread:
      type: object
      properties:
        uid:
          type: string
          description: Идентификатор нитки в системе кодирования Яндекс Расписаний
        title:
          type: string
          description: Название нитки
        number:
          type: string
          description: Номер рейса
        short_title:
          type: string
          description: Сокращенное название нитки
        carrier:
          $ref: '#/components/schemas/Carrier'
        transport_type:
          type: string
          description: Тип транспортного средства
        vehicle:
          type: string
          description: Название транспортного средства
        transport_subtype:
          type: string
          description: Подтип транспорта
        express_type:
          type: string
          description: Признак транспрорта, экспресс или аэроэкспресс
    Codes:
      type: object
      properties:
        icao:
          type: string
          description: Код станции в системе кодирования ICAO
        sirena:
          type: string
          description: Код станции в системе кодирования Sirena
        iata:
          type: string
          description: Код станции в системе кодирования IATA
    Transport_subtype:
      type: object
      properties:
        color:
          type: string
          description: Цвет транспортного средства в шеснадцатизначном формате
        code:
          type: string
          description: Код транспортного средства
        title:
          type: string
          description: Описание подтипа транспортного средства
    Carrier:
      type: object
      properties:
        code:
          type: integer
          description: Код перевозчика в системе кодирования Яндекс Расписаний
        codes:
          $ref: '#/components/schemas/Codes'
        title:
          type: string
          description: Название перевозчика
    Directions:
      type: object
      properties:
        code:
          type: string
          description: Код направления
        title:
          type: string
          description: Название направления
    Stations:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        stations:
          type: array
          items:
            $ref: '#/components/schemas/Station'
    Pagination:
      type: object
      properties:
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
    Station:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        short_title:
          type: string
        popular_title:
          type: string
        code:
          type: string
        lat:
          type: number
        lng:
          type: number
        station_type:
          type: string
        station_type_name:
          type: string
        transport_type:
          type: string
        distance:
          type: number
        majority:
          type: integer
        type_choices:
          $ref: '#/components/schemas/Schedule'
    Schedule:
      type: object
      properties:
        desktop_url:
          type: string
        touch_url:
          type: string
    AllStatios:
      type: object
      properties:
        countries:
          type: array
          item:
            $ref: '#/components/schemas/Countries'
            description: Список стран
    Countries:
      type: object
      properties:
        regions:
          type: array
          item:
            $ref: '#/components/schemas/Regions'
            description: Список регионов
        codes:
          $ref: '#/components/schemas/Codes'
          description: Коды стран
        title:
          type: string
          description: Название страны
    Regions:
      type: object
      properties:
        settlements:
          type: array
          item:
            $ref: '#/components/schemas/Settlements'
            description: Список населенных пунктов
        codes:
          $ref: '#/components/schemas/Codes'
          description: Коды регионов
        title:
          type: string
          description: Название региона
    Settlements:
      type: object
      properties:
        title:
          type: string
          description: Название населенного пункта
        codes:
          $ref: '#/components/schemas/Codes'
          description: Коды населенных пунктов
        stations:
          $ref: '#/components/schemas/AllStations'
          description: Список станций
    AllStations:
      type: object
      properties:
        direction:
          type: string
          description: Направление движания поездов
        codes:
          $ref: '#/components/schemas/CodesStations'
          description: Список кодов станций
        station_type:
          type: string
          description: Тип станции
        title:
          type: string
          description: Название станции
        longitude:
          type: integer
          description: Долгота станции
        transport_type:
          type: string
          description: Тип транспорта
        latitude:
          type: integer
          description: Широта станции
    Stations/Codes:
      type: object
      properties:
        esr_code:
          type: string
          description: Код станции в системе кодирования ESR
        yandex_code:
          type: string
          description: Код станции в системе кодирования Яндекс Расписаний